#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )/.."

if [ ! -d ".react-email" ]; then
	echo "Please create and setup the .react-email directory with yarn email-dev before running this script."
	exit 1
fi

cp .env .react-email/.env
