CREATE TABLE users (
	id UUID NOT NULL PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	email VARCHAR(256) NOT NULL UNIQUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
	id UUID NOT NULL PRIMARY KEY,
	ip INET NOT NULL,
	expires TIMESTAMP NOT NULL,
	user_id UUID REFERENCES users(id)
);
